# Generated by Django 3.2.16 on 2022-11-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.PositiveIntegerField(verbose_name='Пан')),
                ('token', models.PositiveIntegerField(verbose_name='Токен')),
                ('expiry', models.CharField(max_length=50, verbose_name='Дата оканчание')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('verified', models.CharField(max_length=50, verbose_name='Проверинно')),
                ('status', models.CharField(max_length=50, verbose_name='Статус карты')),
                ('fraund_index', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasshotniy_shot', models.PositiveIntegerField()),
                ('inn', models.PositiveIntegerField()),
                ('bank', models.CharField(max_length=50, verbose_name='Банк')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('adress', models.CharField(max_length=120, verbose_name='Адрес')),
                ('contacts', models.CharField(max_length=50, verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Мерчант',
                'verbose_name_plural': 'Мерчанты',
            },
        ),
        migrations.CreateModel(
            name='Paymant_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Система(тип)',
                'verbose_name_plural': 'Системы(типы)',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cтатус',
                'verbose_name_plural': 'Cтатусы',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Трансфер')),
            ],
            options={
                'verbose_name': 'Трансферы',
                'verbose_name_plural': 'Трансфер',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.PositiveIntegerField()),
                ('sum', models.PositiveIntegerField()),
                ('fee', models.PositiveSmallIntegerField()),
                ('detail', models.CharField(max_length=50)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.card')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.status')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус карты')),
                ('fee', models.IntegerField()),
                ('e_pos', models.PositiveIntegerField()),
                ('limit', models.PositiveBigIntegerField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.merchant')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.transaction')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sum', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.CharField(max_length=256)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.card')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.status')),
            ],
            options={
                'verbose_name': 'Платеж ',
                'verbose_name_plural': 'Платежи ',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.merchant'),
        ),
        migrations.AddField(
            model_name='card',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.paymant_system'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('pan', 'merchant')},
        ),
    ]
