# Generated by Django 3.2.16 on 2022-11-07 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221107_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tarif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.tarif'),
            preserve_default=False,
        ),
    ]
