# Generated by Django 3.2.16 on 2022-11-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_payment_tarif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='fee',
        ),
    ]
